name: Crawl and Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install sitemap-generator-cli
        run: npm install -g sitemap-generator-cli
      
      - name: Generate Sitemap
        run: sitemap-generator https://aeblogistics.github.io/Shipping-China-to-USA/ -f sitemap.xml
      
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Auto update sitemap" || exit 0
          git push
